-- Run this in your Supabase SQL Editor

create table public.articles (
  id bigint generated by default as identity primary key,

  hn_id integer unique not null,          -- Original HN ID
  type text,                              -- Type (story, job, etc.)
  by text,                                -- Author username
  posted_at timestamptz,                  -- Posted time
  
  original_title text not null,           -- Original English title
  original_url text,                      -- Original URL (may be null for Ask HN)
  original_text text,                      -- Original text
  score integer,                          -- HN score
  
  kids integer[],                         -- Array of comment IDs
  parent integer,                         -- Parent ID (if applicable)
  poll integer,                           -- Poll ID (if applicable)
  parts integer[],                         -- Array of part IDs (if applicable)
  descendants integer,                     -- Total comment count

  deleted boolean,                        -- Deleted flag
  dead boolean,                            -- Dead flag
  
  raw_content text,                       -- Crawled webpage content or HN text (for RAG)
  image_urls text[],                      -- Array of image URLs from the article

  is_embedded boolean,

  favorites_count integer,
  
  detailed_analysis jsonb,                -- Structured analysis (JSON)
  comment_analysis jsonb,                 -- Comment analysis (JSON)
  
  created_at timestamptz default now()
);

-- Indexes for performance
create index articles_score_idx on public.articles (score desc);
create index articles_posted_at_idx on public.articles (posted_at desc);
create index articles_hn_id_idx on public.articles (hn_id);
create index articles_is_embedded_idx on public.articles (is_embedded)

-- Enable Row Level Security (RLS)
alter table public.articles enable row level security;

-- Create Policy: Allow public read access
create policy "Allow public read access"
on public.articles
for select
to anon, authenticated
using (true);