-- 1. Create conversations table
create table public.conversations (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id bigint references public.articles(id) on delete cascade, -- NULL for Global Chat
  title text, -- Conversation title, e.g. "Discussion about Rust"
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Create indexes to optimize queries
create index conversations_user_article_idx on public.conversations(user_id, article_id);
create index conversations_updated_at_idx on public.conversations(updated_at desc);

-- Enable RLS (Row Level Security)
alter table public.conversations enable row level security;

-- RLS Policy: Users can only view and manage their own conversations
create policy "Users can view their own conversations"
  on public.conversations for select
  using (auth.uid() = user_id);

create policy "Users can insert their own conversations"
  on public.conversations for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own conversations"
  on public.conversations for update
  using (auth.uid() = user_id);

create policy "Users can delete their own conversations"
  on public.conversations for delete
  using (auth.uid() = user_id);


-- 2. Create messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz default now()
);

-- Create indexes
create index messages_conversation_created_idx on public.messages(conversation_id, created_at asc);

-- Enable RLS
alter table public.messages enable row level security;

-- RLS Policy: Users can only access messages that belong to their own conversations
-- Here we use an exists subquery to verify the conversation_id belongs to the current user
create policy "Users can view messages from their conversations"
  on public.messages for select
  using (
    exists (
      select 1 from public.conversations
      where id = messages.conversation_id
      and user_id = auth.uid()
    )
  );

create policy "Users can insert messages into their conversations"
  on public.messages for insert
  with check (
    exists (
      select 1 from public.conversations
      where id = conversation_id
      and user_id = auth.uid()
    )
  );